kksecurity/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^reporter/',include('reporter.urls',namespace='reporter'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

reporter/urls.py
from . import views
from django.conf.urls import url,include

urlpatterns =[
    url('', include('pwa.urls')),
    url(r'^$',views.index.as_view(),name='index'),
    url(r'^checkin/$',views.checkin.as_view(),name='checkin'),
    url(r'^checkout/$',views.checkout.as_view(),name='checkout'),
    url(r'^supervisor/$',views.supervisor.as_view(), name='supervisor'),
    url(r'^guardmap',views.guardmap.as_view(),name='guardmap')

]

reporter/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models;
from django.contrib.gis.db import models



class Pictures(models.Model):
    image_name = models.CharField(max_length=250)
    image = models.ImageField(upload_to='image/%Y/%m/%d/%H/%M/%S', blank=True)
class Worker(models.Model):
    user_id = models.IntegerField(blank=True,null=True)
    longitude = models.FloatField(max_length=250,blank=True,null=True)
    latitude = models.FloatField(max_length=250,blank=True,null=True)
    time = models.CharField(max_length=250,blank=True,null=True)

class Checkout(models.Model):
    user_id = models.IntegerField(blank=True,null=True)
    longitude = models.CharField(max_length=250,blank=True,null=True)
    latitude = models.CharField(max_length=250,blank=True,null=True)
    time = models.CharField(max_length=250,blank=True,null=True)

class Place(models.Model):
    place_name = models.CharField(max_length=250,blank=True,null=True)
    longitude = models.CharField(max_length=250,blank=True,null=True)
    latitude = models.CharField(max_length=250,blank=True,null=True)



# Create your models here.

reporter/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views import generic
from .models import Pictures,Worker,Checkout
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth.models import User
from datetime import datetime


# Create your views here.
class index(generic.FormView):
    def get(self,request,*args,**kwargs):



        icons = Pictures.objects.all().filter(image_name='icon')
        pictures = Pictures.objects.all().filter(image_name='logo')
        #pictures = Pictures.objects.all()
        worker = Worker.objects.all();


        context = {
            'icons':icons,
            'pictures':pictures,
            'user':request.user,
            'workers':worker
        }
        #return HttpResponse(pictures.image_name)
        return render(request, 'reporter/index.html',context)
    def post(self, request, *args, **kwargs):

        form = request.POST

        job_ids = form["job_id"]
        passwords = form["guard_password"]
        user = authenticate(username=job_ids,password=str(passwords))
        #worker = Worker.objects.create(first_name=first_names,second_name=second_names,job_id=job_ids,latitude=latitudes,longitude=longitudes)
        if user.is_authenticated():
            if user is not None:
                if user.is_active:
                    auth_login(request,user)
                    return HttpResponseRedirect('/reporter')

        return HttpResponse(job_ids)
class checkin(generic.FormView):

    def get(self, request, *args, **kwargs):
        return HttpResponse("This is checkin")

    def post(self, request, *args, **kwargs):
        form = request.POST
        userid = form["user_id"]
        time = datetime.now()
        longit = form["user_longitude"]
        lat = form["user_latitude"]

        worker = Worker.objects.create(user_id=userid,longitude=longit,latitude=lat,time=time)
        return HttpResponse(time)

class checkout (generic.FormView):

    def get(self, request, *args, **kwargs):
        return HttpResponse("you have checked out")

    def post(self, request, *args, **kwargs):
        form = request.POST
        userid = form["user_id"]
        time = datetime.now()
        longit = form["user_longitude"]
        lat = form["latitude"]

        check_out = Checkout.objects.create(user_id=userid,longitude=longit,latitude=lat,time=time)
        return HttpResponse(longit)

class supervisor (generic.FormView):

    def get(self, request, *args, **kwargs):

        pictures = Pictures.objects.all().filter(image_name='logo')
        users = User.objects.all()
        worker_in = Worker.objects.all()
        checkouts = Checkout.objects.all()


        context = {
            'pictures':pictures,
            'users':users,
            'workers_in':worker_in,
            'checkouts':checkouts

        }



        #return HttpResponse(checkouts.user_id)
        return  render(request,'reporter/supervisor.html',context)
    def post(self, request, *args, **kwargs):

        form = request.POST
        guard_id = form["guard_id"]

        return render(request,'reporter/guardmap.html')

class guardmap (generic.FormView):
    def get(self, request, *args, **kwargs):


        return render(request, 'reporter/guardmap.html')

    def post(self, request, *args, **kwargs):

        form = request.POST
        longitude = form["longitude"]
        latitude = form["latitude"]

        context = {
            'longitude':longitude,
            'latitude':latitude

        }
        return  render(request,'reporter/guardmap.html',context)

reporter/templates/reporter/base.html
<!DOCTYPE html>
<html lang="en">
{% load pwa %}
{% load static %}
<head>



    <meta charset="utf-8">
    {% load staticfiles %}
    {% block leaflet%} {%endblock%}
    {% progressive_web_app_meta %}
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'reporter/css/bootstrap.min.css'%}">
    <script src="{% static 'reporter/js/jquery-3.2.1.min.js'%}"></script>
    <script src="{% static 'reporter/js/bootstrap.min.js' %}"></script>
    <script src ="{% static 'reporter/js/style.js'%}"></script>
    <link type="text/css" rel="stylesheet" href="{%static 'reporter/css/style.css'%}">
    <script src="http://matchingnotes.com/javascripts/leaflet-google.js"></script>
     <script src="http://maps.google.com/maps/api/js?v=3.2&sensor=false"></script>
    <meta charset="UTF-8">
    <div id="div_logo">

        {%block title%}<title>KKSecurity</title><link rel="icon" href="/media/image/2017/11/28/21/40/08/kk.png" type="image/png">{% endblock %}



{% for picture in pictures %}
     <img src="{{picture.image.url}}" width="200" height="100" class="img-fluid img-rounded" >
{% endfor %}

</div>
</head>
{% block body %}

{% endblock %}

reporter/templates/reporter/guardmap.html
<!DOCTYPE html>
<html>
{% load pwa %}
{% load static %}


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'reporter/css/bootstrap.min.css'%}">
    <script src="{% static 'reporter/js/jquery-3.2.1.min.js'%}"></script>
    <script src="{% static 'reporter/js/bootstrap.min.js' %}"></script>
    <script src ="{% static 'reporter/js/style.js'%}"></script>
    <link type="text/css" rel="stylesheet" href="{%static 'reporter/css/style.css'%}">
    <script src="http://matchingnotes.com/javascripts/leaflet-google.js"></script>
     <script src="http://maps.google.com/maps/api/js?v=3.2&sensor=false"></script>

</head>

<body>

<h1>KKSecurity</h1>

<div id="map" style="width:100%;height:800px;background:yellow"></div>

<script>
    function myMap()
    {

        var myLatlng = new google.maps.LatLng({{latitude}},{{longitude}});
        var mapOptions =
        {
            center: myLatlng,
            zoom: 10,
            mapTypeId: google.maps.MapTypeId.HYBRID
        }
        var map = new google.maps.Map(document.getElementById("map"), mapOptions);
        var marker = new google.maps.Marker(
        {
             position: myLatlng,
             title:"Hello World!"
        });
        marker.setMap(map);

    }
</script>

<script src="https://maps.googleapis.com/maps/api/js?callback=myMap"></script>
<!--
To use this code on your website, get a free API key from Google.
Read more at: https://www.w3schools.com/graphics/google_maps_basic.asp
-->

</body>
</html>

reporter/templates/reporter/index.html
{% extends "reporter/base.html"%}
{%load static%}
{% load leaflet_tags %}
{%block leaflet%}{% leaflet_js%}
{%leaflet_css%}
{% endblock %}

{%block body %}


{%if user.is_anonymous %}
    <script>
        $(document).ready(function(){
        $("#body_content").hide();
        });

    </script>
    <br>
    <br>
<p align="center"> <button type="button" class="btn btn-warning btn-lg" data-toggle="modal" data-target="#div_report_in">Device Not Configured</button></p>
<div id="div_report_in" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times</button>
                <h4 align="center"> <label class="label label-success">Check In</label></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" method="post" action="">
                    {% csrf_token %}

                    <div class="form-group">
                        &nbsp;&nbsp;<label class="label label-info control-label col-sm-2" for="job_id">Job ID</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="job_id" name="job_id">
                        </div>
                    </div>
                    <div class="form-group">
                        &nbsp;&nbsp;<label class="label label-info control-label col-sm-2" for="guard_password">Password</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" id="guard_password" name="guard_password">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Checkin</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>

{%endif%}


<div id="body_content">
<div id="div_logo">
 {% for icon in icons %}
        {%block title%}<title>KKSecurity</title><link rel="icon" href="/media/image/2017/11/27/%09/kk_7ZU2tp1.png" type="image/png">{% endblock %}

{% endfor %}



</div>
<script type="text/javascript">


    function map_init_basic (map,options,x)
    {

     if(navigator.geolocation)
     {

          navigator.geolocation.getCurrentPosition(function(position)
          {
            pos = {
                lat:position.coords.latitude,
                long:position.coords.longitude
            };
            if(pos){
            var x = position.coords.latitude;
            var y = position.coords.longitude;

            L.marker([x, y]).addTo(map);

         }

          });

     }
    }
</script>

{% leaflet_map "map" callback="window.map_init_basic" %}


<script>
    $(document).ready(function(){

        if(navigator.geolocation)
     {

          navigator.geolocation.getCurrentPosition(function(position)
          {
            pos = {
                lat:position.coords.latitude,
                long:position.coords.longitude
            };
            if(pos){
            var x = position.coords.latitude;
            var y = position.coords.longitude;

            //alert([x, y]);

            $("#longitude").val(y);
            $("#latitude").val(x);

            var date = new Date().toString();
            $("#btn_check_in").click(function(){
                $.post("{% url 'reporter:checkin' %}",
                {
                    csrfmiddlewaretoken:'{{csrf_token}}',
                    user_id:'{{user.id}}',
                    user_longitude:y,
                    user_latitude:x
                },
                function(data,success)
                {
                    alert(data);
                    alert(success);
                });

            });

            $("#btn_check_out").click(function()
            {
                $.post("{% url 'reporter:checkout' %}",
                {
                    csrfmiddlewaretoken:'{{csrf_token}}',
                    user_id:'{{user.id}}',
                    user_longitude:y,
                    latitude:x


                },
                function(data,success)
                {
                    alert(data);
                    alert(success);
                });




            });
         }

          });

     }

    });
</script>
        <br>
       <div align="center">
        {%if user.is_authenticated %}

                    <button type="button" id="btn_check_in" class="btn btn-success btn-lg"><span class="glyphicon glyphicon-hand-right">Check In</span></button>
                    <br>
                    <br>
                    <button type="button"  id="btn_check_out" class="btn btn-warning btn-lg"><span class="glyphicon glyphicon-hand-left">Check Out</span> </button>

                    <script>
                        $(document).ready(function(){
                            var x = new Date().toString();
                            alert(x);

                        });
                    </script>
                    <!form action="{% url 'reporter:checkout' %}" method="post">
                        {%csrf_token%}
                        <!input type="hidden" name="user_id" value="{{user.id}}">
                        <!input type="hidden" name="user_longitude" value="123">
                        <!input type="hidden" name="latitude" value="234">

                        <!button type="submit"><!/button>
                    </form>
        {% endif %}
       </div>

</div>
{%endblock%}

reporter/templates/reporter/individual.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

reporter/templates/reporter/supervisor.html
{% extends 'reporter/base.html' %}
{% load static %}
{% load leaflet_tags %}
{%block leaflet%}{% leaflet_js%}
{%leaflet_css%}
{% endblock %}


{% block body %}

<div id="select">
    <br><br>
    <p align="center">
        <button type="button" class="btn btn-success btn-lg" id="btn_checkins"><span class="glyphicon glyphicon-hand-right">Check Ins</span> </button>
        &nbsp;&nbsp;&nbsp;
        <button type="button" class="btn btn-warning btn-lg" id="btn_checkouts"><span class="glyphicon glyphicon-hand-left">Check Outs</span> </button>
        &nbsp;&nbsp;&nbsp;
        <button type="button" class="btn btn-info btn-lg" id="btn_guards" data-toggle="modal" data-target="#div_individual"><span class="glyphicon glyphicon-user">&nbsp;Individual </span> </button>
    </p>

</div>
<script>
    $(document).ready(function(){
        $("#checkouts").hide();
        $("#checkins").hide();
        $("#btn_checkins").click(function(){
             $("#checkouts").fadeOut(1000);
             $("#div_individuals").fadeOut(1000);
            $("#checkins").fadeIn(5000);


        });
        $("#btn_checkouts").click(function(){
            $("#checkins").fadeOut(1000);
            $("#div_individuals").fadeOut(1000);
            $("#checkouts").fadeIn(3000);

        });

    });

</script>
<div id="checkins">

    <div class="table-responsive">
        <table class="table table-responsive table-striped table-bordered table-hover">
            <th class="success"  colspan="6"><h3 align="center"><span >CHECK INS</span></h3></th>
            <tbody>
            <th>
                Guard ID
            </th>
            <th>
                Guard Name
            </th>
            <th>
                Time Cheked In
            </th>
            <th>
                Longitude
            </th>
            <th>
                Latitude
            </th>
            {% for worker in workers_in %}
                <tr>
                    <td>
                        {{worker.user_id}}
                    </td>
                    <td>
                        {%for user in users %}
                            {% if user.id == worker.user_id %}
                        <span class="glyphicon glyphicon-user"> &nbsp; {{user.username}}</span>
                            {% else %}

                            {%endif%}
                        {%endfor%}
                    </td>
                    <td>
                        {{worker.time}}
                    </td>
                    <td>
                        {{worker.longitude}}
                    </td>
                    <td>
                        {{worker.latitude}}
                    </td>
                    <td>
                        <form action="{% url 'reporter:guardmap' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="longitude" value="{{worker.longitude}}">
                            <input type="hidden" name="latitude" value="{{worker.latitude}}">
                            <button type="submit" class="btn btn-info btn-sm" onclick="showLocation('{{worker.longitude}}','{{worker.latitude}}')"><span class="glyphicon glyphicon-globe"> View</span> </button>
                        </form>
                    </td>

                </tr>
            {%endfor%}
            </tbody>
        </table>
    </div>

    <style>
        #checkins,#checkouts
        {
            color:black;
            background:#DCDCDC;
        }
    </style>


</div>

<div id="checkouts">
    <div class="table-responsive">
        <table class="table table-responsive table-striped table-bordered table-hover">
            <th class="success"  colspan="6"><h3 align="center"><span >CHECK OUTS</span></h3></th>
            <tbody>
            <th>
                Guard ID
            </th>
            <th>
                Guard Name
            </th>
            <th>
                Time Cheked In
            </th>
            <th>
                Longitude
            </th>
            <th>
                Latitude
            </th>
            {% for worker in checkouts %}
                <tr>
                    <td>
                        {{worker.user_id}}
                    </td>
                    <td>
                        {%for user in users %}
                            {% if user.id == worker.user_id %}
                        <span class="glyphicon glyphicon-user"> &nbsp; {{user.username}}</span>
                            {% else %}

                            {%endif%}
                        {%endfor%}
                    </td>
                    <td>
                        {{worker.time}}
                    </td>
                    <td>
                        {{worker.longitude}}
                    </td>
                    <td>
                        {{worker.latitude}}
                    </td>
                    <td>
                        <form action="{% url 'reporter:guardmap' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="longitude" value="{{worker.longitude}}">
                            <input type="hidden" name="latitude" value="{{worker.latitude}}">
                            <button type="submit" class="btn btn-info btn-sm" onclick="showLocation('{{worker.longitude}}','{{worker.latitude}}')"><span class="glyphicon glyphicon-globe"> View</span> </button>
                        </form>
                    </td>

                </tr>
            {%endfor%}
            </tbody>
        </table>
    </div>

    <style>
        #checkins
        {
            color:black;
            background:#DCDCDC;
        }
    </style>


</div>

<div id="div_individual" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" data-dismiss="modal">&times;</button>
                <h3 align="center"><label class="label label-success">Individual Detail</label> </h3>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" method="post" action="">
                    {%csrf_token%}
                    <div class="form-group">
                        <label class="label label-info control-label col-sm-2" for="guard_id">Gurad ID</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="guard_id" name="guard_id">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">View</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


</div>


{% endblock %}